export const TRANSFER_PCT_EVALUATION_TYPE = 'transfer_pct';
export const TRANSFER_PCT_EVALUATION_ID = 'percent';
export const TRANSFER_PCT_EVALUATION_TARGET = `${TRANSFER_PCT_EVALUATION_TYPE}:${TRANSFER_PCT_EVALUATION_ID}`;
