export const TRANSFER_PCT_EVALUATION_TYPE = 'transfer_pct';
export const TRANSFER_PCT_EVALUATION_ID = 'percent';
export const TRANSFER_PCT_EVALUATION_TARGET = `${TRANSFER_PCT_EVALUATION_TYPE}:${TRANSFER_PCT_EVALUATION_ID}`;
export const TRANSFER_AMOUNT_EVALUATION_TYPE = 'transfer_amount';
export const TRANSFER_AMOUNT_EVALUATION_ID = 'amount';
export const TRANSFER_AMOUNT_EVALUATION_TARGET = `${TRANSFER_AMOUNT_EVALUATION_TYPE}:${TRANSFER_AMOUNT_EVALUATION_ID}`;
