version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'UTC'
    open-pull-requests-limit: 10
    versioning-strategy: increase
    commit-message:
      prefix: chore
      include: scope
    labels:
      - dependencies
    ignore:
      - dependency-name: '@kingdom-builder/*'
    groups:
      testing-and-quality:
        patterns:
          - 'vitest'
          - '@vitest/*'
          - '@testing-library/*'
          - 'fast-check'
          - 'jsdom'
      linting-and-formatting:
        patterns:
          - 'eslint'
          - 'eslint-*'
          - '@typescript-eslint/*'
          - 'prettier'
      build-tooling:
        patterns:
          - 'vite'
          - '@vitejs/*'
          - 'tsx'
          - 'npm-run-all'
      css-pipeline:
        patterns:
          - 'tailwindcss'
          - 'postcss'
          - 'autoprefixer'
      react-stack:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
      day: 'monday'
      time: '06:00'
      timezone: 'UTC'
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore
      include: scope
    labels:
      - dependencies
