export { ACTIONS, createActionRegistry } from './actions';
export { BUILDINGS, createBuildingRegistry } from './buildings';
export { DEVELOPMENTS, createDevelopmentRegistry } from './developments';
export { POPULATIONS, createPopulationRegistry } from './populations';
export { PHASES, type PhaseDef, type StepDef } from './phases';
export { POPULATION_ROLES } from './populationRoles';
export { RESOURCES } from './resources';
export { STATS } from './stats';
export { TRIGGER_INFO } from './triggers';
export { LAND_ICON, SLOT_ICON } from './land';
export { MODIFIER_INFO } from './modifiers';
export { GAME_START } from './game';
export type { ActionDef } from './actions';
export type { BuildingDef } from './buildings';
export type { DevelopmentDef } from './developments';
export type { PopulationDef, TriggerKey } from './defs';
