version: 2
language: en-US
reviews:
  profile: assertive
  auto_review:
    enabled: true
    auto_incremental_review: true
    base_branches:
      - '.*' # Matches all branches
  path_filters:
    - '**/*'
    - '!node_modules/**'
    - '!dist/**'
    - '!coverage/**'
    - '!artifacts/**'
    - '!packages/**/package-lock.json'
    - '!packages/**/src/**/*.js'
    - '!**/*.d.ts'
    - '!.vscode/**'
    - '!.idea/**'
    - '!.DS_Store'
    - '!tsconfig.tsbuildinfo'
