export * as session from './session';
export * as actions from './actions';

export { Registry } from './registry';
export type { StepDef, PhaseDef } from './phases';
export type { EffectDef } from './effects';
export {
	resourceV2ReconciliationStrategySchema,
	resourceV2DisplayMetadataSchema,
	resourceV2BoundsConfigSchema,
	resourceV2TierStepDisplaySchema,
	resourceV2TierStepSchema,
	resourceV2TierTrackDisplaySchema,
	resourceV2TierTrackSchema,
	resourceV2GroupParentMetadataSchema,
	resourceV2GroupMetadataSchema,
	resourceV2GlobalActionCostSchema,
	resourceV2DefinitionSchema,
	resourceV2GroupDefinitionSchema,
	resourceV2TransferEndpointSchema,
	resourceV2ValueEffectDefinitionSchema,
	resourceV2TransferEffectDefinitionSchema,
	resourceV2BoundAdjustmentDefinitionSchema,
	resourceV2ConfigSchema,
} from './resourceV2/definitions';
export type {
	ResourceV2ReconciliationStrategy,
	ResourceV2DisplayMetadata,
	ResourceV2BoundsConfig,
	ResourceV2TierStepDisplay,
	ResourceV2TierStep,
	ResourceV2TierTrackDisplay,
	ResourceV2TierTrack,
	ResourceV2GroupParentMetadata,
	ResourceV2GroupMetadata,
	ResourceV2GlobalActionCostConfig,
	ResourceV2Definition,
	ResourceV2GroupDefinition,
	ResourceV2TransferEndpointDefinition,
	ResourceV2ValueEffectDefinition,
	ResourceV2TransferEffectDefinition,
	ResourceV2BoundAdjustmentDefinition,
	ResourceV2Config,
} from './resourceV2/definitions';
export {
	applyParamsToEffects,
	coerceActionEffectGroupChoices,
	resolveActionEffects,
} from './effects/resolve';
export type {
	ActionEffectGroupChoice,
	ActionEffectGroupChoiceMap,
	ResolvedActionEffectGroup,
	ResolvedActionEffectGroupOption,
	ResolvedActionEffectGroupStep,
	ResolvedActionEffectStep,
	ResolvedActionEffects,
} from './effects/resolve';
export type { EvaluatorDef } from './evaluators';
export type {
	AttackTarget,
	ResourceAttackTarget,
	StatAttackTarget,
	BuildingAttackTarget,
	AttackCalcOptions,
	AttackLogOwner,
	AttackPowerLog,
	AttackNumericTargetLog,
	ResourceAttackEvaluationTargetLog,
	StatAttackEvaluationTargetLog,
	BuildingAttackEvaluationTargetLog,
	AttackEvaluationTargetLog,
	AttackEvaluationLog,
	AttackResourceDiff,
	AttackStatDiff,
	AttackPlayerDiff,
	AttackOnDamageLogEntry,
	AttackLog,
} from './effects/attack';
export {
	TRANSFER_AMOUNT_EVALUATION_ID,
	TRANSFER_AMOUNT_EVALUATION_TARGET,
	TRANSFER_AMOUNT_EVALUATION_TYPE,
	TRANSFER_PCT_EVALUATION_ID,
	TRANSFER_PCT_EVALUATION_TARGET,
	TRANSFER_PCT_EVALUATION_TYPE,
} from './effects/resource_transfer';
export {
	requirementSchema,
	effectSchema,
	actionCategorySchema,
	actionEffectGroupSchema,
	actionEffectSchema,
	actionSchema,
	buildingSchema,
	developmentSchema,
	populationSchema,
	startConfigSchema,
	gameConfigSchema,
	validateGameConfig,
	phaseStepSchema,
	phaseSchema,
} from './config/schema';
export type {
	RequirementConfig,
	EffectConfig,
	ActionCategoryConfig,
	ActionEffectGroup,
	ActionEffectGroupOption,
	ActionEffect,
	ActionConfig,
	BuildingConfig,
	DevelopmentConfig,
	PopulationConfig,
	PlayerStartConfig,
	StartConfig,
	StartModeConfig,
	StartModesConfig,
	GameConfig,
	PhaseStepConfig,
	PhaseConfig,
} from './config/schema';
export type {
	PhaseSkipConfig,
	PhaseSkipStep,
	PassiveMetadata,
	PassiveRemovalMetadata,
	PassiveSourceMetadata,
	TierRange,
	TierPassivePreview,
	TierPassiveTextTokens,
	TierDisplayMetadata,
	TierEffect,
	HappinessTierDefinition,
	WinConditionOutcome,
	WinConditionDefinition,
	WinConditionDisplay,
	WinConditionTrigger,
	WinConditionResult,
	CorePhaseIds,
	RuleSet,
} from './services';
export type {
	SessionPlayerId,
	SessionStatSourceLink,
	SessionStatSourceMeta,
	SessionStatSourceContribution,
	SessionLandSnapshot,
	SessionPassiveSummary,
	SessionPlayerStateSnapshot,
	SessionGameConclusionSnapshot,
	SessionGameSnapshot,
	SessionAdvanceSkipSourceSnapshot,
	SessionAdvanceSkipSnapshot,
	SessionPhaseStepDefinition,
	SessionPhaseDefinition,
	SessionAdvanceResult,
	PlayerSnapshotDeltaBucket,
	SimulateUpcomingPhasesIds,
	SimulateUpcomingPhasesOptions,
	SimulateUpcomingPhasesResult,
	SessionPassiveRecordSnapshot,
	SessionRuleSnapshot,
	SessionRecentResourceGain,
	SessionSnapshot,
	SessionEffectLogMap,
	SessionPassiveEvaluationModifierMap,
	SessionMetadataDescriptor,
	SessionMetadataFormat,
	SessionOverviewTokenCategoryName,
	SessionOverviewTokenMap,
	SessionOverviewHero,
	SessionOverviewListItem,
	SessionOverviewParagraphSection,
	SessionOverviewListSection,
	SessionOverviewSection,
	SessionOverviewMetadata,
	SessionPhaseMetadata,
	SessionPhaseStepMetadata,
	SessionTriggerMetadata,
	SessionSnapshotMetadata,
	SessionMetadataSnapshot,
	SessionActionDefinitionSummary,
	SessionActionCostMap,
	SessionRequirementFailure,
	SessionActionRequirementList,
} from './session';
export type {
	SessionIdentifier,
	SessionPlayerNameMap,
	SessionCreateRequest,
	SessionCreateResponse,
	SessionStateResponse,
	SessionAdvanceRequest,
	SessionAdvanceResponse,
	SessionSetDevModeRequest,
	SessionSetDevModeResponse,
	SessionRegistriesPayload,
	SessionResourceDefinition,
	SerializedRegistry,
	SessionActionCategoryRegistry,
	SessionUpdatePlayerNameRequest,
	SessionUpdatePlayerNameResponse,
	SessionActionCostRequest,
	SessionActionCostResponse,
	SessionActionRequirementRequest,
	SessionActionRequirementResponse,
	SessionActionOptionsRequest,
	SessionActionOptionsResponse,
	SessionRunAiAction,
	SessionRunAiRequest,
	SessionRunAiResponse,
	SessionSimulateRequest,
	SessionSimulateResponse,
	SessionRuntimeConfigResponse,
	SessionMetadataSnapshotResponse,
} from './session/contracts';
export type { SessionGateway } from './session/gateway';
export type {
	ActionEffectChoice,
	ActionChoiceMap,
	ActionParametersPayload,
	ActionExecuteRequest,
	ActionTraceLandSnapshot,
	ActionPlayerSnapshot,
	ActionTrace,
	ActionExecuteSuccessResponse,
	ActionExecuteErrorResponse,
	ActionExecuteResponse,
} from './actions/contracts';
export {
	sessionIdSchema,
	sessionPlayerNameMapSchema,
	sessionCreateRequestSchema,
	sessionCreateResponseSchema,
	sessionStateResponseSchema,
	sessionAdvanceRequestSchema,
	sessionAdvanceResponseSchema,
	sessionSetDevModeRequestSchema,
	sessionSetDevModeResponseSchema,
	sessionUpdatePlayerNameRequestSchema,
	sessionUpdatePlayerNameResponseSchema,
	sessionActionCostRequestSchema,
	sessionActionCostResponseSchema,
	sessionActionRequirementRequestSchema,
	sessionActionRequirementResponseSchema,
	sessionActionOptionsRequestSchema,
	sessionActionOptionsResponseSchema,
	sessionRunAiRequestSchema,
	sessionRunAiResponseSchema,
	sessionSimulateRequestSchema,
	sessionSimulateResponseSchema,
	sessionRegistriesSchema,
	runtimeConfigResponseSchema,
	sessionMetadataSnapshotSchema,
	sessionMetadataSnapshotResponseSchema,
} from './config/session_contracts';
export {
	actionEffectChoiceSchema,
	actionChoiceMapSchema,
	actionParametersSchema,
	actionTraceLandSnapshotSchema,
	actionPlayerSnapshotSchema,
	actionTraceSchema,
	actionRequirementFailureSchema,
	actionExecuteRequestSchema,
	actionExecuteSuccessResponseSchema,
	actionExecuteErrorResponseSchema,
	actionExecuteResponseSchema,
} from './config/action_contracts';
