export * as session from './session';
export * as actions from './actions';

export { Registry } from './registry';
export type { StepDef, PhaseDef } from './phases';
export type { EffectDef } from './effects';
export {
	applyParamsToEffects,
	coerceActionEffectGroupChoices,
	resolveActionEffects,
} from './effects/resolve';
export type {
	ActionEffectGroupChoice,
	ActionEffectGroupChoiceMap,
	ResolvedActionEffectGroup,
	ResolvedActionEffectGroupOption,
	ResolvedActionEffectGroupStep,
	ResolvedActionEffectStep,
	ResolvedActionEffects,
} from './effects/resolve';
export type { EvaluatorDef } from './evaluators';
export type {
	AttackTarget,
	ResourceAttackTarget,
	StatAttackTarget,
	BuildingAttackTarget,
	AttackCalcOptions,
	AttackLogOwner,
	AttackPowerLog,
	AttackNumericTargetLog,
	ResourceAttackEvaluationTargetLog,
	StatAttackEvaluationTargetLog,
	BuildingAttackEvaluationTargetLog,
	AttackEvaluationTargetLog,
	AttackEvaluationLog,
	AttackResourceDiff,
	AttackStatDiff,
	AttackPlayerDiff,
	AttackOnDamageLogEntry,
	AttackLog,
} from './effects/attack';
export {
	TRANSFER_PCT_EVALUATION_ID,
	TRANSFER_PCT_EVALUATION_TARGET,
	TRANSFER_PCT_EVALUATION_TYPE,
} from './effects/resource_transfer';
export {
	requirementSchema,
	effectSchema,
	actionEffectGroupSchema,
	actionEffectSchema,
	actionSchema,
	buildingSchema,
	developmentSchema,
	populationSchema,
	startConfigSchema,
	gameConfigSchema,
	validateGameConfig,
	phaseStepSchema,
	phaseSchema,
} from './config/schema';
export type {
	RequirementConfig,
	EffectConfig,
	ActionEffectGroup,
	ActionEffectGroupOption,
	ActionEffect,
	ActionConfig,
	BuildingConfig,
	DevelopmentConfig,
	PopulationConfig,
	PlayerStartConfig,
	StartConfig,
	StartModeConfig,
	StartModesConfig,
	GameConfig,
	PhaseStepConfig,
	PhaseConfig,
} from './config/schema';
export type {
	PhaseSkipConfig,
	PhaseSkipStep,
	PassiveMetadata,
	PassiveRemovalMetadata,
	PassiveSourceMetadata,
	TierRange,
	TierPassivePreview,
	TierPassiveTextTokens,
	TierDisplayMetadata,
	TierEffect,
	HappinessTierDefinition,
	WinConditionOutcome,
	WinConditionDefinition,
	WinConditionDisplay,
	WinConditionTrigger,
	WinConditionResult,
	CorePhaseIds,
	RuleSet,
} from './services';
export type {
	SessionPlayerId,
	SessionStatSourceLink,
	SessionStatSourceMeta,
	SessionStatSourceContribution,
	SessionLandSnapshot,
	SessionPassiveSummary,
	SessionPlayerStateSnapshot,
	SessionGameConclusionSnapshot,
	SessionGameSnapshot,
	SessionAdvanceSkipSourceSnapshot,
	SessionAdvanceSkipSnapshot,
	SessionPhaseStepDefinition,
	SessionPhaseDefinition,
	SessionAdvanceResult,
	SessionPassiveRecordSnapshot,
	SessionRuleSnapshot,
	SessionRecentResourceGain,
	SessionSnapshot,
	SessionEffectLogMap,
	SessionPassiveEvaluationModifierMap,
	SessionMetadataDescriptor,
	SessionPhaseMetadata,
	SessionPhaseStepMetadata,
	SessionTriggerMetadata,
	SessionSnapshotMetadata,
	SessionActionDefinitionSummary,
	SessionActionCostMap,
	SessionRequirementFailure,
	SessionActionRequirementList,
} from './session';
export type {
	SessionIdentifier,
	SessionPlayerNameMap,
	SessionCreateRequest,
	SessionCreateResponse,
	SessionStateResponse,
	SessionAdvanceRequest,
	SessionAdvanceResponse,
	SessionSetDevModeRequest,
	SessionSetDevModeResponse,
	SessionRegistriesPayload,
	SessionResourceDefinition,
	SerializedRegistry,
	SessionUpdatePlayerNameRequest,
	SessionUpdatePlayerNameResponse,
} from './session/contracts';
export type { SessionGateway } from './session/gateway';
export type {
	ActionEffectChoice,
	ActionChoiceMap,
	ActionParametersPayload,
	ActionDescribeOptions,
	ActionDescribeRequest,
	ActionDescribeResponse,
	ActionExecuteRequest,
	ActionTraceLandSnapshot,
	ActionPlayerSnapshot,
	ActionTrace,
	ActionExecuteSuccessResponse,
	ActionExecuteErrorResponse,
	ActionExecuteResponse,
} from './actions/contracts';
export {
	sessionIdSchema,
	sessionPlayerNameMapSchema,
	sessionCreateRequestSchema,
	sessionCreateResponseSchema,
	sessionStateResponseSchema,
	sessionAdvanceRequestSchema,
	sessionAdvanceResponseSchema,
	sessionSetDevModeRequestSchema,
	sessionSetDevModeResponseSchema,
	sessionUpdatePlayerNameRequestSchema,
	sessionUpdatePlayerNameResponseSchema,
} from './config/session_contracts';
export {
	actionEffectChoiceSchema,
	actionChoiceMapSchema,
	actionParametersSchema,
	actionTraceLandSnapshotSchema,
	actionPlayerSnapshotSchema,
	actionTraceSchema,
	actionRequirementFailureSchema,
	actionDescribeOptionsSchema,
	actionDescribeRequestSchema,
	actionDescribeResponseSchema,
	actionExecuteRequestSchema,
	actionExecuteSuccessResponseSchema,
	actionExecuteErrorResponseSchema,
	actionExecuteResponseSchema,
} from './config/action_contracts';
