#!/usr/bin/env sh

# Exit on errors
set -e

# Run lint-staged on changed files
npx lint-staged

# Run type checking and linting
npm run check

# Run tests after check passes
npm test
if [ -n "$SONAR_TOKEN" ]; then
  npx sonar-scanner -Dsonar.token=$SONAR_TOKEN
else
  npx sonar-scanner -Dsonar.scanner.skip=true
fi
