name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, 'project/**', 'codex/**']

env:
  # Kill the slow audit/fund calls that were timing out (503) in your logs
  NPM_CONFIG_AUDIT: 'false'
  NPM_CONFIG_FUND: 'false'
  # Optional: silence progress bars in CI
  NPM_CONFIG_PROGRESS: 'false'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'npm'

      # Robust install: prefer lockfile, skip audit/fund, retry on transient failures
      - name: Install deps
        run: |
          for i in 1 2 3; do
            npm ci --prefer-offline --no-progress && break || {
              echo "Install failed (attempt $i). Retrying in 10s..."; sleep 10;
            }
          done

      - run: npm run check
      - run: npm run test:ci
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: |
          for i in 1 2 3; do
            npm ci --prefer-offline --no-progress && break || {
              echo "Install failed (attempt $i). Retrying in 10s..."; sleep 10;
            }
          done

      - run: npm run check
      - run: npm run build
