name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('playwright.config.ts') }}
          restore-keys: |
            ${{ runner.os }}-playwright-
      - run: npm ci
      - run: npm run format --check
      - run: npm run type-check
      - run: npm test

      - run: npm run test:coverage
      # Install only the Chrome browser. Dependencies are already present on
      # the GitHub runner, so we skip the slow `--with-deps` flag.
      - run: npx playwright install chrome
      - run: npm run e2e
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run format --check
      - run: npm test
      - run: npm run type-check
      - run: npm run build
