name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, 'project/**', 'codex/**']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci || npm i
      - run: npm run check
      - run: npm run test:ci
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci || npm i
      - run: npm run check
      - run: npm run build
